**Arithmetic Operations**

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [14]:
l = [10,20,30,40]
arr = np.array(l)

If we want to add 10 in each element:

In [13]:
arr + 10

array([20, 30, 40, 50])

**Deep and Shallow Copy**

In [17]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a[4:6] * 10

array([50, 60])

In [19]:
a 
b = a

In [20]:
b[0] = 22
b

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operations**

In [22]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])                       

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
B

array([[5, 6],
       [7, 8]])

In [25]:
A @ B

array([[19, 22],
       [43, 50]])

In [28]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

Stacking Array

In [30]:
A

array([[1, 2],
       [3, 4]])

In [31]:
B

array([[5, 6],
       [7, 8]])

We cannot stack two arrays 

We can stack two arrays or two vectors

In [34]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [35]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting Array**

In [41]:
import numpy as np 

In [46]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
c = np.hsplit(c,2)
c

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
c = np.arange(16).reshape(4,4)

np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]