**Numpy Indexing and Slicing of Vectors**

In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6]

np.int64(17)

In [4]:
arr[1:5]

array([12, 13, 14, 15])

**Numpy Indexing and Slicing of Matrix**

In [5]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [6]:
arr[0]

array([1, 2, 3, 4, 5])

In [7]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [8]:
arr[0,0]

np.int64(1)

In [9]:
arr[5,4]

np.int64(30)

In [10]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [12]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

**Boolean Indexing**

In [8]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [10]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])