In [5]:
import numpy as np

**Bold Array Creation**

In [7]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [10]:
a = ([1,2,3.5,"Hello"])
a

[1, 2, 3.5, 'Hello']

In [11]:
np.array(a) # All the datatypes are converted to string data type

array(['1', '2', '3.5', 'Hello'], dtype='<U32')

In [13]:
a = [1,2,3.5] # All datatypes will be converted into float datatype
a

[1, 2, 3.5]

In [ ]:
# TWO THINGS ARE THERE IN ARRAYS AND LIST : VECTORS AND MATRIX

# Vectors are created in single one dimensional space.
# [1,2,3,4,5] 

# Matrix are two dimensional there are multiple rows and columns.
#[[1,2,3],[4,5,6],[7,8,9]] This is multi dimensional list

# Mutiple dimensional are not supported in list

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# This list is looking like a one dimensional, what if we
# convert this in array

In [14]:
np.array(l) # It will look like a two dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [16]:
#Range fucntion
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.zeros(4)
arr # This is one dimensional or vector

array([0., 0., 0., 0.])

In [18]:
arr = np.zeros((4,8))
arr # This will generate matrix

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [24]:
#LINSPACE

arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [20]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [21]:
arr = np.linspace(1,10,3)
arr

array([ 1. ,  5.5, 10. ])

**Random Genration function**

In [25]:
np.random.rand(5) # Here values are between 1 and 0, this is a concept of
# normalization in statistics

array([0.90944686, 0.10469965, 0.92665098, 0.72443843, 0.4995035 ])

In [26]:
#If we want standardization values
np.random.randn(10)

array([ 0.19991982, -0.63534471, -1.09600244,  0.67004457, -0.51394031,
       -0.26579679, -1.15392066, -1.60120955, -0.67265745, -3.38512659])

In [29]:
np.random.randint(10,20,10) # It will generate 10 random numbers between 10 and 20

array([14, 11, 11, 14, 11, 18, 18, 12, 15, 10], dtype=int32)

**Array Attributes**

Attributes - Attributes are kind of variables defined inside class.
Methods - Methods are functions defined inside a class.

Attributes are accessed, but methods are called.

In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.shape #Its an attribute

(3, 3)

In [34]:
arr.size

9

In [35]:
arr.dtype

dtype('int64')

**Array Methods**

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.min() #Methods

np.int64(1)

In [38]:
arr.max()

np.int64(9)

In [39]:
arr.sum()

np.int64(45)

In [40]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [41]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [42]:
arr.mean()

np.float64(5.0)

In [43]:
arr.std()

np.float64(2.581988897471611)

In [22]:
arr.argmax()

np.int64(2)

In [25]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
import numpy as np

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.min()

np.int64(1)

In [9]:
arr.max()

np.int64(9)

In [10]:
arr.std()

np.float64(2.581988897471611)

In [27]:
arr.sum()

np.int64(45)

In [31]:
np.sum(arr,axis=1) #Rows

array([ 6, 15, 24])

In [12]:
np.sum(arr,axis=0) #Columns

array([12, 15, 18])

In [32]:
arr.argmax() #Index of maximum element

np.int64(8)

In [33]:
arr.argmin() #Index of minimum element

np.int64(0)

**Reshaping and Resizing**

In [34]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
arr.reshape(4,5) # All the values are converted in rows and colunmns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])